// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/**
 * Primary content in Banner → Primary
 *
 */
interface BannerSliceDefaultPrimary {
  /**
   * Title field in *Banner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Description field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Background field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.background
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  background: prismic.ImageField<never>;
}
/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in Banner → Primary
 *
 */
interface BannerSliceHalfBannerPrimary {
  /**
   * Title field in *Banner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Description field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Background field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.background
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  background: prismic.ImageField<never>;
}
/**
 * Half Banner variation for Banner Slice
 *
 * - **API ID**: `halfBanner`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceHalfBanner = prismic.SharedSliceVariation<
  "halfBanner",
  Simplify<BannerSliceHalfBannerPrimary>,
  never
>;
/**
 * Slice variation for *Banner*
 *
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceHalfBanner;
/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;
/**
 * Primary content in BannerSlice → Primary
 *
 */
interface BannerSliceSliceDefaultSlicePrimary {
  /**
   * Title field in *BannerSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: banner_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Description field in *BannerSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: banner_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Background field in *BannerSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_slice.primary.background
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  background: prismic.ImageField<never>;
}
/**
 * Default slice variation for BannerSlice Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `BannerSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Simplify<BannerSliceSliceDefaultSlicePrimary>,
  never
>;
/**
 * Primary content in BannerSlice → Primary
 *
 */
interface BannerSliceSliceHalfBannerPrimary {
  /**
   * Title field in *BannerSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: banner_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Description field in *BannerSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: banner_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Background field in *BannerSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_slice.primary.background
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  background: prismic.ImageField<never>;
}
/**
 * Half Banner variation for BannerSlice Slice
 *
 * - **API ID**: `halfBanner`
 * - **Description**: `BannerSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceSliceHalfBanner = prismic.SharedSliceVariation<
  "halfBanner",
  Simplify<BannerSliceSliceHalfBannerPrimary>,
  never
>;
/**
 * Slice variation for *BannerSlice*
 *
 */
type BannerSliceSliceVariation =
  | BannerSliceSliceDefaultSlice
  | BannerSliceSliceHalfBanner;
/**
 * BannerSlice Shared Slice
 *
 * - **API ID**: `banner_slice`
 * - **Description**: `BannerSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceSlice = prismic.SharedSlice<
  "banner_slice",
  BannerSliceSliceVariation
>;
/**
 * Item in Card → Items
 *
 */
export interface CardSliceDefaultItem {
  /**
   * Card Title field in *Card → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card.items[].card_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  card_title: prismic.TitleField;
  /**
   * Card Description field in *Card → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card.items[].card_description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  card_description: prismic.RichTextField;
}
/**
 * Default variation for Card Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CardSliceDefaultItem>
>;
/**
 * Slice variation for *Card*
 *
 */
type CardSliceVariation = CardSliceDefault;
/**
 * Card Shared Slice
 *
 * - **API ID**: `card`
 * - **Description**: `Card`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardSlice = prismic.SharedSlice<"card", CardSliceVariation>;
/**
 * Item in CardSlice → Items
 *
 */
export interface CardSliceSliceDefaultSliceItem {
  /**
   * Card Title field in *CardSlice → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].cardTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  cardTitle: prismic.TitleField;
  /**
   * Card Description field in *CardSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_slice.items[].cardDescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  cardDescription: prismic.RichTextField;
}
/**
 * Default slice variation for CardSlice Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `CardSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardSliceSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Record<string, never>,
  Simplify<CardSliceSliceDefaultSliceItem>
>;
/**
 * Slice variation for *CardSlice*
 *
 */
type CardSliceSliceVariation = CardSliceSliceDefaultSlice;
/**
 * CardSlice Shared Slice
 *
 * - **API ID**: `card_slice`
 * - **Description**: `CardSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardSliceSlice = prismic.SharedSlice<
  "card_slice",
  CardSliceSliceVariation
>;
/**
 * Item in ExperienceCards → Items
 *
 */
export interface ExperienceCardsSliceDefaultItem {
  /**
   * Company Name field in *ExperienceCards → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards.items[].company_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  company_name: prismic.TitleField;
  /**
   * Job Title field in *ExperienceCards → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards.items[].job_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  job_title: prismic.TitleField;
  /**
   * Date String field in *ExperienceCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards.items[].date_string
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  date_string: prismic.KeyTextField;
  /**
   * Description field in *ExperienceCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Default variation for ExperienceCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExperienceCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ExperienceCardsSliceDefaultItem>
>;
/**
 * Slice variation for *ExperienceCards*
 *
 */
type ExperienceCardsSliceVariation = ExperienceCardsSliceDefault;
/**
 * ExperienceCards Shared Slice
 *
 * - **API ID**: `experience_cards`
 * - **Description**: `ExperienceCards`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExperienceCardsSlice = prismic.SharedSlice<
  "experience_cards",
  ExperienceCardsSliceVariation
>;
/**
 * Item in ExperienceCardsSlice → Items
 *
 */
export interface ExperienceCardsSliceSliceDefaultSliceItem {
  /**
   * Company Name field in *ExperienceCardsSlice → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards_slice.items[].companyName
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  companyName: prismic.TitleField;
  /**
   * Job Title field in *ExperienceCardsSlice → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards_slice.items[].jobTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  jobTitle: prismic.TitleField;
  /**
   * Date String field in *ExperienceCardsSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards_slice.items[].dateString
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  dateString: prismic.KeyTextField;
  /**
   * Description field in *ExperienceCardsSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_cards_slice.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Default slice variation for ExperienceCardsSlice Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `ExperienceCardsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExperienceCardsSliceSliceDefaultSlice =
  prismic.SharedSliceVariation<
    "default-slice",
    Record<string, never>,
    Simplify<ExperienceCardsSliceSliceDefaultSliceItem>
  >;
/**
 * Slice variation for *ExperienceCardsSlice*
 *
 */
type ExperienceCardsSliceSliceVariation = ExperienceCardsSliceSliceDefaultSlice;
/**
 * ExperienceCardsSlice Shared Slice
 *
 * - **API ID**: `experience_cards_slice`
 * - **Description**: `ExperienceCardsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExperienceCardsSliceSlice = prismic.SharedSlice<
  "experience_cards_slice",
  ExperienceCardsSliceSliceVariation
>;
/**
 * Primary content in FeaturedImage → Primary
 *
 */
interface FeaturedImageSliceDefaultSlicePrimary {
  /**
   * Title field in *FeaturedImage → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Headline field in *FeaturedImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
  /**
   * Link field in *FeaturedImage → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.ContentRelationshipField<"home-page" | "page">;
  /**
   * Link Label field in *FeaturedImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.primary.linkLabel
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  linkLabel: prismic.KeyTextField;
  /**
   * Featured Image field in *FeaturedImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.primary.featuredImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  featuredImage: prismic.ImageField<never>;
}
/**
 * Default slice variation for FeaturedImage Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `FeaturedImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturedImageSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Simplify<FeaturedImageSliceDefaultSlicePrimary>,
  never
>;
/**
 * Slice variation for *FeaturedImage*
 *
 */
type FeaturedImageSliceVariation = FeaturedImageSliceDefaultSlice;
/**
 * FeaturedImage Shared Slice
 *
 * - **API ID**: `featured_image`
 * - **Description**: `FeaturedImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturedImageSlice = prismic.SharedSlice<
  "featured_image",
  FeaturedImageSliceVariation
>;
/**
 * Primary content in FullWidthImage → Primary
 *
 */
interface FullWidthImageSliceDefaultSlicePrimary {
  /**
   * image field in *FullWidthImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default slice variation for FullWidthImage Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `FullWidthImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullWidthImageSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Simplify<FullWidthImageSliceDefaultSlicePrimary>,
  never
>;
/**
 * Slice variation for *FullWidthImage*
 *
 */
type FullWidthImageSliceVariation = FullWidthImageSliceDefaultSlice;
/**
 * FullWidthImage Shared Slice
 *
 * - **API ID**: `full_width_image`
 * - **Description**: `FullWidthImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FullWidthImageSlice = prismic.SharedSlice<
  "full_width_image",
  FullWidthImageSliceVariation
>;
/**
 * Primary content in GoogleForm → Primary
 *
 */
interface GoogleFormSliceDefaultPrimary {
  /**
   * Google Form Link field in *GoogleForm → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: google_form.primary.google_form_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  google_form_link: prismic.LinkField;
}
/**
 * Default variation for GoogleForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GoogleFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GoogleFormSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *GoogleForm*
 *
 */
type GoogleFormSliceVariation = GoogleFormSliceDefault;
/**
 * GoogleForm Shared Slice
 *
 * - **API ID**: `google_form`
 * - **Description**: `GoogleForm`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GoogleFormSlice = prismic.SharedSlice<
  "google_form",
  GoogleFormSliceVariation
>;
/**
 * Primary content in GoogleFormSlice → Primary
 *
 */
interface GoogleFormSliceSliceDefaultSlicePrimary {
  /**
   * Google Form Link field in *GoogleFormSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: google_form_slice.primary.googleFormLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  googleFormLink: prismic.LinkField;
}
/**
 * Default slice variation for GoogleFormSlice Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `GoogleFormSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GoogleFormSliceSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Simplify<GoogleFormSliceSliceDefaultSlicePrimary>,
  never
>;
/**
 * Slice variation for *GoogleFormSlice*
 *
 */
type GoogleFormSliceSliceVariation = GoogleFormSliceSliceDefaultSlice;
/**
 * GoogleFormSlice Shared Slice
 *
 * - **API ID**: `google_form_slice`
 * - **Description**: `GoogleFormSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GoogleFormSliceSlice = prismic.SharedSlice<
  "google_form_slice",
  GoogleFormSliceSliceVariation
>;
/**
 * Primary content in Text → Primary
 *
 */
interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Text*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;
/**
 * Primary content in TextSlice → Primary
 *
 */
interface TextSliceSliceDefaultSlicePrimary {
  /**
   * Text field in *TextSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_slice.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default slice variation for TextSlice Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `TextSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Simplify<TextSliceSliceDefaultSlicePrimary>,
  never
>;
/**
 * Slice variation for *TextSlice*
 *
 */
type TextSliceSliceVariation = TextSliceSliceDefaultSlice;
/**
 * TextSlice Shared Slice
 *
 * - **API ID**: `text_slice`
 * - **Description**: `TextSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceSlice = prismic.SharedSlice<
  "text_slice",
  TextSliceSliceVariation
>;
/**
 * Item in Timeline → Items
 *
 */
export interface TimelineSliceDefaultItem {
  /**
   * Date String field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].date_string
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  date_string: prismic.KeyTextField;
  /**
   * Title field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Subtitle field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField;
  /**
   * Description field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismic.KeyTextField;
}
/**
 * Default variation for Timeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TimelineSliceDefaultItem>
>;
/**
 * Slice variation for *Timeline*
 *
 */
type TimelineSliceVariation = TimelineSliceDefault;
/**
 * Timeline Shared Slice
 *
 * - **API ID**: `timeline`
 * - **Description**: `Timeline`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TimelineSlice = prismic.SharedSlice<
  "timeline",
  TimelineSliceVariation
>;
/**
 * Item in TimelineSlice → Items
 *
 */
export interface TimelineSliceSliceDefaultSliceItem {
  /**
   * Date String field in *TimelineSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_slice.items[].dateString
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  dateString: prismic.KeyTextField;
  /**
   * Title field in *TimelineSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_slice.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * Subtitle field in *TimelineSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_slice.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField;
  /**
   * Description field in *TimelineSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_slice.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismic.KeyTextField;
}
/**
 * Default slice variation for TimelineSlice Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `TimelineSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TimelineSliceSliceDefaultSlice = prismic.SharedSliceVariation<
  "default-slice",
  Record<string, never>,
  Simplify<TimelineSliceSliceDefaultSliceItem>
>;
/**
 * Slice variation for *TimelineSlice*
 *
 */
type TimelineSliceSliceVariation = TimelineSliceSliceDefaultSlice;
/**
 * TimelineSlice Shared Slice
 *
 * - **API ID**: `timeline_slice`
 * - **Description**: `TimelineSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TimelineSliceSlice = prismic.SharedSlice<
  "timeline_slice",
  TimelineSliceSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client;
  }
  namespace Content {
    export type {
      BannerSliceDefaultPrimary,
      BannerSliceDefault,
      BannerSliceHalfBannerPrimary,
      BannerSliceHalfBanner,
      BannerSliceVariation,
      BannerSlice,
      BannerSliceSliceDefaultSlicePrimary,
      BannerSliceSliceDefaultSlice,
      BannerSliceSliceHalfBannerPrimary,
      BannerSliceSliceHalfBanner,
      BannerSliceSliceVariation,
      BannerSliceSlice,
      CardSliceDefaultItem,
      CardSliceDefault,
      CardSliceVariation,
      CardSlice,
      CardSliceSliceDefaultSliceItem,
      CardSliceSliceDefaultSlice,
      CardSliceSliceVariation,
      CardSliceSlice,
      ExperienceCardsSliceDefaultItem,
      ExperienceCardsSliceDefault,
      ExperienceCardsSliceVariation,
      ExperienceCardsSlice,
      ExperienceCardsSliceSliceDefaultSliceItem,
      ExperienceCardsSliceSliceDefaultSlice,
      ExperienceCardsSliceSliceVariation,
      ExperienceCardsSliceSlice,
      FeaturedImageSliceDefaultSlicePrimary,
      FeaturedImageSliceDefaultSlice,
      FeaturedImageSliceVariation,
      FeaturedImageSlice,
      FullWidthImageSliceDefaultSlicePrimary,
      FullWidthImageSliceDefaultSlice,
      FullWidthImageSliceVariation,
      FullWidthImageSlice,
      GoogleFormSliceDefaultPrimary,
      GoogleFormSliceDefault,
      GoogleFormSliceVariation,
      GoogleFormSlice,
      GoogleFormSliceSliceDefaultSlicePrimary,
      GoogleFormSliceSliceDefaultSlice,
      GoogleFormSliceSliceVariation,
      GoogleFormSliceSlice,
      TextSliceDefaultPrimary,
      TextSliceDefault,
      TextSliceVariation,
      TextSlice,
      TextSliceSliceDefaultSlicePrimary,
      TextSliceSliceDefaultSlice,
      TextSliceSliceVariation,
      TextSliceSlice,
      TimelineSliceDefaultItem,
      TimelineSliceDefault,
      TimelineSliceVariation,
      TimelineSlice,
      TimelineSliceSliceDefaultSliceItem,
      TimelineSliceSliceDefaultSlice,
      TimelineSliceSliceVariation,
      TimelineSliceSlice,
    };
  }
}
