// This file is generated by Prismic local builder. Update with care!

export { default as BannerSlice } from './BannerSlice'
export { default as CardSlice } from './CardSlice'
export { default as FeaturedImage } from './FeaturedImage'
export { default as FullWidthImage } from './FullWidthImage'
export { default as GoogleFormSlice } from './GoogleFormSlice'
export { default as TextSlice } from './TextSlice'
export { default as TimelineSlice } from './TimelineSlice'
