// This file is generated by Prismic local builder. Update with care!

export { default as BannerSlice } from './BannerSlice'
export { default as FeaturedImage } from './FeaturedImage'
export { default as FullWidthImage } from './FullWidthImage'
