// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  card: dynamic(() => import("./Card")),
  experience_cards: dynamic(() => import("./ExperienceCards")),
  featured_image: dynamic(() => import("./FeaturedImage")),
  full_width_image: dynamic(() => import("./FullWidthImage")),
  google_form: dynamic(() => import("./GoogleForm")),
  text: dynamic(() => import("./Text")),
  timeline: dynamic(() => import("./Timeline")),
};
